# Mbed OS CMake configuration file.
# This contains all of the information needed for CMake to compile and use Mbed OS.
# It was extracted from the Mbed configuration files when you originally configured this project.
# AUTOGENERATED by "mbed-cmake/configure_for_target.py -a mbed_app.json -x . -i .mbedignore SensorBoard NUCLEO_H743ZI2".  DO NOT EDIT!

set(MBED_TARGET_LIST
   SensorBoard
   NUCLEO_H743ZI2)

